application: ubertool-demo
version: master
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: numpy
  version: latest
- name: django
  version: "1.5"
- name: PIL
  version: latest
- name: matplotlib
  version: latest
- name: ssl
  version: "latest" 

builtins:
- django_wsgi: on

env_variables:
  UBERTOOL_REST_SERVER: 'http://localhost:80'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: wsgi.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.gz
- ^(.*/)?.*\.aux
- ^(.*/)?.*\.xcf
- ^(.*/)?.*\.php
- ^(.*/)?.*\.bak
- ^(.*/)?.*\.inc
- ^(.*/)?.*\.dark
- ^(.*/)?.*\.nofill
- ^(.*/)?.*\.SDR
- ^(.*/)?.*\MIT-LICENSE
- ^(.*/)?.*\LGPL-LICENSE